### ISSUE TITLE
Create Stage Instance

### ISSUE THREAD

**Issue by MatthewAlner** [4lejandrito/diary#6]
Create Stage Instance
- [x] Ensure the app builds and deploy on heroku
- [x] Create heroku instance: https://diario-tardin.herokuapp.com/#
- [x] Deploy to heroku on every push

**Comment by 4lejandrito** [comment]
Check it out! 

https://diario-tardin.herokuapp.com/#

**Comment by 4lejandrito** [comment]
Done. This is our stage instance now:
https://diary-stage.herokuapp.com/#
A deploy will happend on every push

**Comment by MatthewAlner** [comment]
No such app?
